### ISSUE TITLE
Newsletter page text needs update

### ISSUE THREAD

**Issue by Didier-Lalli** [hpe-dev-incubator/hpe-dev-portal#200]
Should be: 

Subscribe to our HPE Developer Newsletter to stay up-to-date on the newest HPE Dev Community activities, posts, and tutorials.

Instead of:

Join our mailing list to stay up-to-date on the newest blog posts and tutorials.
Sign up for the HPE Developer Newsletter!

**Comment by drensing** [comment]
I just looked at the website. It still has "Join our mailing list to stay up-to-date on the newest blog posts and tutorials. Sign up for the HPE Developer Newsletter!" instead of what Didier and I both suggested it be changed to, which is "Subscribe to our HPE Developer Newsletter to stay up-to-date on the newest HPE Dev Community activities, posts, and tutorials."

**Comment by reddypramod85** [comment]
Updated the copy.
