### ISSUE TITLE
Unable to find the preview for a new blog contribution

### ISSUE THREAD

**Issue by choukden** [hpe-dev-incubator/hpe-dev-portal#711]
@jaygiang  Hi Jay,

We received a new contribution (a blog post) from an HPE employee (Ezmeral): Kiran Kumar Mavatoor.
For unknown reason, we are not able to see the blog post in the preview page

PR: https://github.com/hpe-dev-incubator/hpe-dev-portal/pull/710

This morning, I managed to find the preview URL, but I am no longer able to see the blog post anymore in the Preview page

Here is the blog post: https://deploy-preview-710--hpe-dev-portal.netlify.app/blog/accessing-hpe-data-fabric-s3-storage-from-spring-boot-s3-micro-service-deployed-in-k3s-cluster/

Could you please help investigate why the blog post is not visible in the preview web site?

CC: @Didier-Lalli

**Comment by jaygiang** [comment]
Hi @choukden, 

You should now see Kiran's blog when you select **HPE Ezmeral Data Fabric** within the **Platforms dropdown** https://deploy-preview-710--hpe-dev-portal.netlify.app/blog. 

I don't believe this was showing before, but when I tried and clicked on the `hpe-ezmeral-data-fabric` tag within the blog https://deploy-preview-710--hpe-dev-portal.netlify.app/blog/accessing-hpe-data-fabric-s3-storage-from-spring-boot-s3-micro-service-deployed-in-k3s-cluster/, it suddenly showed up. I think we should check if this same situation happens when there is another preview deploy for Kiran's blog. 

As for Kiran's blog not showing up in the **All** tab, it looks like it's set as a `featureBlog:true`, so a `priority` needs to be set.

**Comment by choukden** [comment]
@jaygiang 
Thank you very much for looking into this.
Kiran submitted another preview deployment in NetLify CMS and he set the FeatureBlog to False.
I can now see his blog post in the "Blog page".
So it sounds like setting Featureblog to true without a priority is causing such issue.

Thanks
Denis

CC: @Didier-Lalli

**Comment by choukden** [comment]
Yep,. I asked him earlier today to change the tag. 
@jaygiang

**Comment by jaygiang** [comment]
Thanks @choukden!
