### ISSUE TITLE
Open external links in a new tab

### ISSUE THREAD

**Issue by Didier-Lalli** [hpe-dev-incubator/hpe-dev-portal#716]
Could we change the behavior of the site so that any external link should be opened in a new tab

**Comment by Didier-Lalli** [comment]
This is something we need for the Our API page, so I'm thinking we should make it a high priority.

**Comment by choukden** [comment]
Agree!!!

**Comment by jaygiang** [comment]
@Didier-Lalli @choukden

After doing some research, it looks like in order for us to make links in the markdown body open in new tab, we will need to migrate our `.md` files to use `.mdx` files: https://www.gatsbyjs.com/docs/how-to/routing/migrate-remark-to-mdx/

I can go forward with this, but we will need to do some thorough testing of the whole website due to this change.

**Comment by jaygiang** [comment]
@Didier-Lalli @choukden 

External links now work for in Markdown in Blogs. 

Please test/review when possible: https://deploy-preview-885--hpe-dev-portal.netlify.app/blog/accessing-dtap-in-pods/

**Comment by Didier-Lalli** [comment]
Was this done by migrating to .mdx? Or did you find another option? Works very well.

**Comment by choukden** [comment]
@jaygiang 
Thank you very much. It looks to work very well.

@Didier-Lalli 
The PR #885 is probably related to this.

**Comment by jaygiang** [comment]
Thanks @choukden, yes that is the correct PR. 

@Didier-Lalli luckily no .mdx needed. I was able to add the props through the Grommet Markdown component. 

I will go ahead and push this live.
