### ISSUE TITLE
New blog not showing up in All

### ISSUE THREAD

**Issue by Didier-Lalli** [hpe-dev-incubator/hpe-dev-portal#742]
There has been several cases (Didier, Dale), whew w new blog doesn't show up after being merged. After clearing cache, it might come back, but also we noticed it's visible in Others (In the case of Sir Hackington), but not in All. And I think this has started to happen after we implemented the blog category view. It's a problem as we cannot ask everyone to refresh their cache :-)

**Comment by Didier-Lalli** [comment]
Could it be because it has no tag?

**Comment by jaygiang** [comment]
@Didier-Lalli Thanks for bringing this to my attention. The issue is that when a user clicks on `Load More`, it actually saves all the blog data into Local Storage. It's saved into Local Storage because when a user clicks on a blog, then goes back to the Blog page, the code uses the Local Storage data to scroll to the position where the blog was originally clicked.

I've added a conditional statement to clear Local Storage if a new blog is detected, so it should be working now and users should not need to refresh their cache.
